export const state = {
  geminiKey: localStorage.getItem('gemini_key') || (import.meta.env && import.meta.env.VITE_GEMINI_KEY) || '',
  weatherKey: localStorage.getItem('weather_key') || (import.meta.env && import.meta.env.VITE_WEATHER_KEY) || '',
  prefLang: localStorage.getItem('pref_lang') || 'English',
  version: '3.1.2-ELITE',
  currentImage: null,
  location: null,
  isScanning: false,
  isStreaming: false,
  activeTab: 'dashboard',
  chatSession: null,
  currentUser: null,
  lastDiagnosis: null,
  map: null,
  markers: [],
  heatmapLayers: [],
  showHeatmap: false,
  batchImages: [],
  isBatchMode: false,
  isFieldMode: false,
  localModel: null,
  availableClasses: [],
  currentRiskPolygon: null,
  activeLearningQueue: [],
  modelLabels: [
    'Healthy', 
    'Rice Blast', 'Rice Healthy', 
    'Wheat Rust', 'Wheat Healthy', 
    'Corn Smut', 'Corn Healthy', 
    'Grape Black Rot', 'Grape Healthy',
    'Coffee Leaf Rust', 'Coffee Healthy', 
    'Tea Blight', 'Tea Healthy', 
    'Cocoa Swollen Shoot', 'Cocoa Healthy',
    'Sugarcane Red Rot', 'Sugarcane Healthy',
    'Cotton Boll Rot', 'Cotton Healthy',
    'Soybean Rust', 'Soybean Healthy',
    'Banana Sigatoka', 'Banana Healthy',
    'Citrus Greening', 'Citrus Healthy',
    'Mango Anthracnose', 'Mango Healthy',
    'Strawberry Leaf Spot', 'Strawberry Healthy',
    'Potato Early Blight', 'Potato Late Blight', 'Potato Healthy',
    'Tomato Bacterial Spot', 'Tomato Early Blight', 'Tomato Late Blight', 'Tomato healthy',
    'Pepper Bell Bacterial Spot', 'Pepper Bell Healthy',
    'Rubber Leaf Fall', 'Rubber Healthy',
    'Peach Bacterial Spot', 'Peach Healthy',
    'Cherry Powdery Mildew', 'Cherry Healthy',
    'Oil Palm Ganoderma', 'Oil Palm Healthy',
    'Apple Scab', 'Apple Black Rot', 'Apple Cedar Rust', 'Apple Healthy'
  ],
  treatments: {},
  currentResult: null,
  vmsEnabled: false,
  survey: {
    active: false,
    scans: [],
    startTime: null
  },
  iot: {
    moisture: 42,
    ph: 6.8,
    nitrogen: 'Optimal',
    status: 'SIMULATED'
  },
  drone: {
    active: false,
    missionID: null,
    path: [],
    marker: null,
    polyline: null,
    progress: 0,
    interval: null
  }
};
